name: Docker image

on:
  push:

jobs:
  build-push:
    uses: EO-DataHub/eoap-gen/.github/workflows/generate-reusable.yml@main
    with:
      config: eoap-gen-config.yml
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
